//Gerenciamento_de_banco_de_dados
spring.application.name=TaskApplication
spring.datasource.url=jdbc:mysql://localhost:3306/suabase?useSSL=false&serverTimezone=UTC
spring.source.username=root
spring.source.password=admin
spring.jpa.hibernate.ddl-aut=update
spring.jpa.show-sql=true
spring.jpa.propeies.hibernate.format_sql=true